### PR TITLE
Fix segmentation fault due to improperly implemented threading

### LINKED ISSUE #8: php example watch callback cause segmentation fault frequently，but sometimes success
php:5.4.41
Zookeeper:3.4.9

array(2) {
  [0] =>
  string(3) "001"
  [1] =>
  string(3) "002"
}
[3]    12649 segmentation fault (core dumped)  /apps/php/bin/php zookeeper.php

### PR DESCRIPTION
**Pull request by jbboehr**
This PR is intended to fix #8 by re-implementing the execution of callbacks passed to libzookeeper via the method used by the `pcntl` extension. Previously, callbacks would be executed in the thread started by zookeeper. Now callbacks will be executed in the original PHP thread either when calling `zookeeper_dispatch()`, by using `declare(ticks=1)`, or,  in PHP 7.1 or greater, automatically using VM interrupts.

### CODE REVIEW

**Comment by Timandes** [comment]
👍

**Comment by jbboehr** [comment]
Looks like the `oneshot` parameter is not currently working, and the internal `callbacks` may no longer be needed - requires some further review/work.

File: php_zookeeper.c [hunk 1]
```diff
@@ -967,13 +1007,123 @@ static void php_zk_completion_marshal(int rc, const void *context)
...
+	// Allocate new item
+	struct php_zk_pending_marshal *p = calloc(1, sizeof(struct php_zk_pending_marshal));
+	p->cb_data = context;
+	p->type = type;
+	p->state = state;
+	p->path = strdup(path);
+	p->cb_data = cb_data;
+
+	// Add to list
+	if( ZK_G(head) && ZK_G(tail) ) {
```
Comment (Timandes) [inline php_zookeeper.c:1098]: If we are using NTS version of PHP, is this `ZK_G` safe enough to access the global variable `head` N `tail`?

Comment (jbboehr) [reply php_zookeeper.c:1098]: I not sure NTS vs ZTS matters too much here, I believe ZTS is mainly required for environments where PHP is being run within many threads in the same process. [[1]](https://jpauli.github.io/2017/01/12/threads-and-php.html#how-php-treats-requests)

I was considering adding a mutex to this block, but as there were none in pcntl, and portability may be an issue, I did not.

The pcntl extension may be a bit different, I guess signals probably use software interrupts instead of threads.

In any case, the conservative option would be to add a mutex here.
